# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('feed_url', models.URLField(max_length=500, unique=True)),
                ('public_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('guid', models.CharField(db_index=True, max_length=500, unique=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feed')),
            ],
            options={
                'ordering': ('-date_modified',),
            },
        ),
    ]
